Add SmallDrop player
2kodevs/domaino pull request #11
Opened 2020-12-05 23:11 UTC by stdevRulo

2020-12-05 23:58 UTC, cicr99 approved these changes

2020-12-06 00:33 UTC, stdevAntiD2ta approved these changes, later dismissed

2020-12-06 00:34 UTC, cicr99 requested changes

2020-12-06 00:34 UTC, cicr99 commented on domaino/players/strategies/small_drop.py
> +    """ Always drop piece with highest score
```suggestion
    """ Always drop piece with lowest score
```

2020-12-06 00:36 UTC, stdevAntiD2ta approved these changes

2020-12-06 00:37 UTC, cicr99 approved these changes

2020-12-06 00:37 UTC, merged